INSERT INTO questions (question, option_a, option_b, option_c, option_d, correct_option) VALUES
('Glavni grad Srbije je?', 'Novi Sad', 'Niš', 'Beograd', 'Kragujevac', 'C'),
('Koliko kontinenata ima na Zemlji?', '5', '6', '7', '8', 'C'),
('Koja planeta je najbliža Suncu?', 'Venera', 'Merkur', 'Mars', 'Jupiter', 'B'),
('Ko je napisao delo "Na Drini ćuprija"?', 'Ivo Andrić', 'Mesa Selimović', 'Branko Ćopić', 'Danilo Kiš', 'A'),
('Koja država je osvojila Svetsko prvenstvo u fudbalu 2018?', 'Brazil', 'Nemačka', 'Francuska', 'Argentina', 'C'),
('Najveća reka u Srbiji je?', 'Morava', 'Sava', 'Dunav', 'Drina', 'C'),
('Koji je hemijski simbol za vodu?', 'O2', 'H2O', 'CO2', 'NaCl', 'B'),
('Koja godina se smatra početkom Prvog svetskog rata?', '1912', '1914', '1916', '1918', 'B'),
('Koliko minuta traje fudbalsko poluvreme?', '40', '45', '50', '60', 'B'),
('Najviša planina na svetu je?', 'K2', 'Mont Blanc', 'Everest', 'Kilimandžaro', 'C'),

('Koja država ima najviše stanovnika?', 'Indija', 'SAD', 'Kina', 'Rusija', 'C'),
('Ko je izumeo sijalicu?', 'Nikola Tesla', 'Thomas Edison', 'Albert Einstein', 'Isaac Newton', 'B'),
('Koliko je 9 x 9?', '72', '81', '90', '99', 'B'),
('Koja boja nastaje mešanjem plave i žute?', 'Zelena', 'Ljubičasta', 'Narandžasta', 'Braon', 'A'),
('Koji je najveći okean?', 'Atlantski', 'Indijski', 'Tihi', 'Severni ledeni', 'C'),

('Koja je valuta u Srbiji?', 'Euro', 'Dinar', 'Forinta', 'Leva', 'B'),
('Koliko dana ima prestupna godina?', '365', '366', '364', '360', 'B'),
('Ko je autor Mona Lize?', 'Michelangelo', 'Leonardo da Vinci', 'Picasso', 'Van Gogh', 'B'),
('Koji sport koristi reket?', 'Fudbal', 'Košarka', 'Tenis', 'Odbojka', 'C'),
('Koja životinja je poznata kao kralj džungle?', 'Tigar', 'Lav', 'Slon', 'Leopard', 'B'),

('Koji je glavni grad Francuske?', 'Lion', 'Marsej', 'Pariz', 'Tuluz', 'C'),
('Koliko meseci ima godina?', '10', '11', '12', '13', 'C'),
('Koji je najveći sisar?', 'Slon', 'Plavi kit', 'Nosorog', 'Žirafa', 'B'),
('Koja država je domaćin Olimpijskih igara 2024?', 'Japan', 'Francuska', 'SAD', 'Kina', 'B'),
('Koji instrument ima dirke?', 'Gitara', 'Violina', 'Klavir', 'Truba', 'C'),

('Koja boja ima semafor za "kreni"?', 'Crvena', 'Žuta', 'Zelena', 'Plava', 'C'),
('Koliko strana ima trougao?', '2', '3', '4', '5', 'B'),
('Koja ptica ne leti?', 'Orao', 'Vrabac', 'Pingvin', 'Lasta', 'C'),
('Koji je najveći kontinent?', 'Evropa', 'Afrika', 'Azija', 'Amerika', 'C'),
('Koja je najmanja država na svetu?', 'Monako', 'San Marino', 'Vatikan', 'Andora', 'C'),
('Koji gas je najzastupljeniji u Zemljinoj atmosferi?', 'Kiseonik', 'Ugljen-dioksid', 'Azot', 'Vodonik', 'C'),
('Koliko igrača ima košarkaški tim na terenu?', '4', '5', '6', '7', 'B'),
('Koji je glavni grad Italije?', 'Milano', 'Napulj', 'Rim', 'Torino', 'C'),
('Ko je autor dela "Zločin i kazna"?', 'Tolstoj', 'Dostojevski', 'Čehov', 'Puškin', 'B'),
('Koja planeta je poznata kao Crvena planeta?', 'Venera', 'Mars', 'Jupiter', 'Saturn', 'B'),
('Koji je najveći organ u ljudskom telu?', 'Srce', 'Mozak', 'Koža', 'Jetra', 'C'),
('Koja reka protiče kroz London?', 'Temza', 'Sena', 'Rajna', 'Dunav', 'A'),
('Koliko je 100 / 4?', '20', '25', '30', '40', 'B'),
('Koji kontinent nema stalno stanovništvo?', 'Afrika', 'Evropa', 'Antarktik', 'Australija', 'C'),
('Koja životinja je simbol Australije?', 'Koala', 'Kengur', 'Emu', 'Dingo', 'B');
